export const DECK = [
  {
    suite: "♣",
    rank: "2",
    value: 2,
    img: "images/clover-2.jpg",
  },
  {
    suite: "♣",
    rank: "3",
    value: 3,
    img: "images/clover-3.jpg",
  },
  {
    suite: "♣",
    rank: "4",
    value: 4,
    img: "images/clover-4.jpg",
  },
  {
    suite: "♣",
    rank: "5",
    value: 5,
    img: "images/clover-5.jpg",
  },
  {
    suite: "♣",
    rank: "6",
    value: 6,
    img: "images/clover-6.jpg",
  },
  {
    suite: "♣",
    rank: "7",
    value: 7,
    img: "images/clover-7.jpg",
  },
  {
    suite: "♣",
    rank: "8",
    value: 8,
    img: "images/clover-8.jpg",
  },
  {
    suite: "♣",
    rank: "9",
    value: 9,
    img: "images/clover-9.jpg",
  },
  {
    suite: "♣",
    rank: "10",
    value: 10,
    img: "images/clover-10.jpg",
  },
  {
    suite: "♣",
    rank: "J",
    value: 11,
    img: "images/clover-j.jpg",
  },
  {
    suite: "♣",
    rank: "Q",
    value: 13,
    img: "images/clover-q.jpg",
  },
  {
    suite: "♣",
    rank: "K",
    value: 15,
    img: "images/clover-k.jpg",
  },
  {
    suite: "♣",
    rank: "A",
    value: 17,
    img: "images/clover-a.jpg",
  },
  {
    suite: "♦",
    rank: "2",
    value: 2,
    img: "images/tile-2.jpg",
  },
  {
    suite: "♦",
    rank: "3",
    value: 3,
    img: "images/tile-3.jpg",
  },
  {
    suite: "♦",
    rank: "4",
    value: 4,
    img: "images/tile-4.jpg",
  },
  {
    suite: "♦",
    rank: "5",
    value: 5,
    img: "images/tile-5.jpg",
  },
  {
    suite: "♦",
    rank: "6",
    value: 6,
    img: "images/tile-6.jpg",
  },
  {
    suite: "♦",
    rank: "7",
    value: 7,
    img: "images/tile-7.jpg",
  },
  {
    suite: "♦",
    rank: "8",
    value: 8,
    img: "images/tile-8.jpg",
  },
  {
    suite: "♦",
    rank: "9",
    value: 9,
    img: "images/tile-9.jpg",
  },
  {
    suite: "♦",
    rank: "10",
    value: 10,
    img: "images/tile-10.jpg",
  },
  {
    suite: "♦",
    rank: "J",
    value: 11,
    img: "images/tile-j.jpg",
  },
  {
    suite: "♦",
    rank: "Q",
    value: 11,
    img: "images/tile-q.jpg",
  },
  {
    suite: "♦",
    rank: "K",
    value: 11,
    img: "images/tile-k.jpg",
  },
  {
    suite: "♦",
    rank: "A",
    value: 11,
    img: "images/tile-a.jpg",
  },
  {
    suite: "♥",
    rank: "2",
    value: 2,
    img: "images/heart-2.jpg",
  },
  {
    suite: "♥",
    rank: "3",
    value: 3,
    img: "images/heart-3.jpg",
  },
  {
    suite: "♥",
    rank: "4",
    value: 4,
    img: "images/heart-4.jpg",
  },
  {
    suite: "♥",
    rank: "5",
    value: 5,
    img: "images/heart-5.jpg",
  },
  {
    suite: "♥",
    rank: "6",
    value: 6,
    img: "images/heart-6.jpg",
  },
  {
    suite: "♥",
    rank: "7",
    value: 7,
    img: "images/heart-7.jpg",
  },
  {
    suite: "♥",
    rank: "8",
    value: 8,
    img: "images/heart-8.jpg",
  },
  {
    suite: "♥",
    rank: "9",
    value: 9,
    img: "images/heart-9.jpg",
  },
  {
    suite: "♥",
    rank: "10",
    value: 10,
    img: "images/heart-10.jpg",
  },
  {
    suite: "♥",
    rank: "J",
    value: 11,
    img: "images/heart-j.jpg",
  },
  {
    suite: "♥",
    rank: "Q",
    value: 11,
    img: "images/heart-q.jpg",
  },
  {
    suite: "♥",
    rank: "K",
    value: 11,
    img: "images/heart-k.jpg",
  },
  {
    suite: "♥",
    rank: "A",
    value: 11,
    img: "images/heart-a.jpg",
  },
  {
    suite: "♠",
    rank: "2",
    value: 2,
    img: "images/spade-2.jpg",
  },
  {
    suite: "♠",
    rank: "3",
    value: 3,
    img: "images/spade-3.jpg",
  },
  {
    suite: "♠",
    rank: "4",
    value: 4,
    img: "images/spade-4.jpg",
  },
  {
    suite: "♠",
    rank: "5",
    value: 5,
    img: "images/spade-5.jpg",
  },
  {
    suite: "♠",
    rank: "6",
    value: 6,
    img: "images/spade-6.jpg",
  },
  {
    suite: "♠",
    rank: "7",
    value: 7,
    img: "images/spade-7.jpg",
  },
  {
    suite: "♣",
    rank: "8",
    value: 8,
    img: "images/spade-8.jpg",
  },
  {
    suite: "♠",
    rank: "9",
    value: 9,
    img: "images/spade-9.jpg",
  },
  {
    suite: "♠",
    rank: "10",
    value: 10,
    img: "images/spade-10.jpg",
  },
  {
    suite: "♠",
    rank: "J",
    value: 11,
    img: "images/spade-j.jpg",
  },
  {
    suite: "♠",
    rank: "Q",
    value: 13,
    img: "images/spade-q.jpg",
  },
  {
    suite: "♠",
    rank: "K",
    value: 15,
    img: "images/spade-k.jpg",
  },
  {
    suite: "♠",
    rank: "A",
    value: 17,
    img: "images/spade-a.jpg",
  },
  {
    suite: "★",
    rank: "D",
    value: 21,
    img: "images/donsol-1.jpg",
  },
  {
    suite: "★",
    rank: "D",
    value: 21,
    img: "images/donsol-2.jpg",
  },
];
